# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/sentences_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SentencesWindow_UI(object):
    def setupUi(self, SentencesWindow_UI):
        SentencesWindow_UI.setObjectName("SentencesWindow_UI")
        SentencesWindow_UI.resize(519, 165)
        self.centralwidget = QtWidgets.QWidget(SentencesWindow_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 109))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineItalian = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineItalian.setObjectName("lineItalian")
        self.horizontalLayout_2.addWidget(self.lineItalian)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineChinese = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineChinese.setFont(font)
        self.lineChinese.setObjectName("lineChinese")
        self.horizontalLayout_3.addWidget(self.lineChinese)
        self.labelValidTranslation = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelValidTranslation.sizePolicy().hasHeightForWidth())
        self.labelValidTranslation.setSizePolicy(sizePolicy)
        self.labelValidTranslation.setMinimumSize(QtCore.QSize(50, 0))
        self.labelValidTranslation.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelValidTranslation.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelValidTranslation.setText("")
        self.labelValidTranslation.setObjectName("labelValidTranslation")
        self.horizontalLayout_3.addWidget(self.labelValidTranslation)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnInvio = QtWidgets.QPushButton(self.layoutWidget)
        self.btnInvio.setAutoDefault(True)
        self.btnInvio.setDefault(True)
        self.btnInvio.setObjectName("btnInvio")
        self.horizontalLayout.addWidget(self.btnInvio)
        self.btnSkip = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSkip.setAutoDefault(True)
        self.btnSkip.setObjectName("btnSkip")
        self.horizontalLayout.addWidget(self.btnSkip)
        self.btnReveal = QtWidgets.QPushButton(self.layoutWidget)
        self.btnReveal.setObjectName("btnReveal")
        self.horizontalLayout.addWidget(self.btnReveal)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnReset = QtWidgets.QPushButton(self.layoutWidget)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout.addWidget(self.btnReset)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        SentencesWindow_UI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SentencesWindow_UI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 23))
        self.menubar.setObjectName("menubar")
        SentencesWindow_UI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SentencesWindow_UI)
        self.statusbar.setObjectName("statusbar")
        SentencesWindow_UI.setStatusBar(self.statusbar)

        self.retranslateUi(SentencesWindow_UI)
        QtCore.QMetaObject.connectSlotsByName(SentencesWindow_UI)

    def retranslateUi(self, SentencesWindow_UI):
        _translate = QtCore.QCoreApplication.translate
        SentencesWindow_UI.setWindowTitle(_translate("SentencesWindow_UI", "MainWindow"))
        self.lineItalian.setPlaceholderText(_translate("SentencesWindow_UI", "romanization"))
        self.lineChinese.setPlaceholderText(_translate("SentencesWindow_UI", "translation"))
        self.btnInvio.setText(_translate("SentencesWindow_UI", "Send"))
        self.btnSkip.setText(_translate("SentencesWindow_UI", "Skip"))
        self.btnReveal.setText(_translate("SentencesWindow_UI", "Reveal"))
        self.btnReset.setText(_translate("SentencesWindow_UI", "Reset"))
