# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/secondary_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(392, 120)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelWord = QtWidgets.QLabel(self.centralwidget)
        self.labelWord.setGeometry(QtCore.QRect(10, 10, 281, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelWord.setFont(font)
        self.labelWord.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelWord.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelWord.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWord.setObjectName("labelWord")
        self.lineRoman = QtWidgets.QLineEdit(self.centralwidget)
        self.lineRoman.setGeometry(QtCore.QRect(210, 40, 81, 26))
        self.lineRoman.setReadOnly(True)
        self.lineRoman.setObjectName("lineRoman")
        self.btnInvio = QtWidgets.QPushButton(self.centralwidget)
        self.btnInvio.setGeometry(QtCore.QRect(210, 80, 81, 26))
        self.btnInvio.setAutoDefault(True)
        self.btnInvio.setDefault(True)
        self.btnInvio.setObjectName("btnInvio")
        self.labelCharacter = QtWidgets.QLabel(self.centralwidget)
        self.labelCharacter.setGeometry(QtCore.QRect(10, 39, 191, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCharacter.sizePolicy().hasHeightForWidth())
        self.labelCharacter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(48)
        self.labelCharacter.setFont(font)
        self.labelCharacter.setAcceptDrops(True)
        self.labelCharacter.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelCharacter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelCharacter.setScaledContents(True)
        self.labelCharacter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCharacter.setObjectName("labelCharacter")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelWord.setText(_translate("MainWindow", "TextLabel"))
        self.btnInvio.setText(_translate("MainWindow", "Send"))
        self.labelCharacter.setText(_translate("MainWindow", "女"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
